### ISSUE TITLE
Reg form page seems to be not fully in UTF-8

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-registration-form#3]
With the reg sys and the backend API now completely in UTF-8 encoding, we should ensure the reg form app also exclusively uses UTF-8 encoding.

Maybe it's just the sample data set, but when I browse to the input form as currently deployed on our regtest server (URLs see telegram group) in Firefox, I get a broken encoding on the street field, it says ```placeholder="TeststraÃŸe 24"``` in the page source. I'm guessing we need to set utf-8 as page encoding and possibly also as form encoding (not sure about the latter part).

**Comment by Fenmar** [comment]
This did not happen in my local development environment because the server included the content type in the response header. The header in question read

    content-type: text/html; charset=UTF-8

The testserver does not include the charset section. So I guess we could fix this in the backend. I also pushed a frontend side change to include the charset meta tag. Could you try this out and let me know if that fixes the issue?

**Comment by Jumpy-Squirrel** [comment]
Tested with other changes on 2019-12-02. Seems to work now.
